name: web_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  go_router: ^14.6.3
  google_fonts: ^6.2.1
  http: ^1.2.2
  shelf_router: ^1.1.4
  shelf_web_socket: ^2.0.1
  url_launcher: ^6.3.1
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

